# Generated by Django 5.2.2 on 2026-06-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionMIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_whatsapp', models.CharField(help_text='Número de WhatsApp del interlocutor (ej: 5216444475422)', max_length=20)),
                ('rol', models.CharField(choices=[('user', 'Auditor'), ('mia', 'MIA')], max_length=10)),
                ('contenido', models.TextField()),
                ('intencion', models.CharField(blank=True, choices=[('ANALISIS_DOCUMENTO', 'Análisis de Documento'), ('CONSULTA_NORMATIVA', 'Consulta Normativa PBIP'), ('CONSULTA_ESTADO', 'Consulta Estado Expediente'), ('CONVERSACION_GENERAL', 'Conversación General'), ('RECORDATORIO', 'Recordatorio/Alerta')], max_length=30, null=True)),
                ('metadatos', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensaje de Conversación MIA',
                'verbose_name_plural': 'Conversaciones MIA',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['numero_whatsapp', 'timestamp'], name='portal_clie_numero__eb4e6a_idx')],
            },
        ),
    ]
