# Generated by Django 5.2.2 on 2026-06-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0008_requisitobuque_motivo_rechazo'),
        ('portal_cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaProactiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('ALTA_INCOMPLETA', 'Alta de naviera incompleta'), ('DOCS_PBIP_FALTANTES', 'Documentos PBIP faltantes'), ('DOC_PROXIMO_VENCER', 'Documento próximo a vencer'), ('COTIZACION_SIN_RESPUESTA', 'Cotización sin respuesta'), ('RESUMEN_DIARIO', 'Resumen diario para auditor')], max_length=30)),
                ('mensaje_enviado', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('canal', models.CharField(default='whatsapp', max_length=20)),
                ('exito', models.BooleanField(default=True)),
                ('reintentos', models.IntegerField(default=0)),
                ('buque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='naviera_registro.buque')),
                ('naviera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='naviera_registro.naviera')),
            ],
            options={
                'unique_together': {('naviera', 'buque', 'tipo_alerta', 'fecha_envio')},
            },
        ),
    ]
