# Generated by Django 5.2.2 on 2026-06-16 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0009_naviera_telefono_contacto'),
        ('portal_cliente', '0002_alertaproactiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos_formulario', models.JSONField(default=dict)),
                ('tipo_servicio', models.CharField(blank=True, choices=[('verificacion', 'Verificación'), ('evaluacion', 'Evaluación')], max_length=20, null=True)),
                ('rango_buque', models.CharField(blank=True, choices=[('grande', 'Grandes y Complejos (>80m)'), ('mediano', 'Medianos y Especializados (≤80m, múltiples cubiertas)'), ('pequeno', 'Pequeños y Especializados (≤80m, cubierta simple)')], max_length=20, null=True)),
                ('eslora', models.DecimalField(blank=True, decimal_places=2, help_text='Eslora en metros', max_digits=6, null=True)),
                ('notas_auditor', models.TextField(blank=True, help_text='Notas o ajustes del auditor')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('buque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naviera_registro.buque')),
                ('documento_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='naviera_registro.documentoentregable')),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naviera_registro.naviera')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TarifarioGMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('verificacion', 'Verificación'), ('evaluacion', 'Evaluación')], max_length=20)),
                ('rango_buque', models.CharField(choices=[('grande', 'Grandes y Complejos (>80m)'), ('mediano', 'Medianos y Especializados (≤80m, múltiples cubiertas)'), ('pequeno', 'Pequeños y Especializados (≤80m, cubierta simple)')], max_length=20)),
                ('anio', models.IntegerField()),
                ('costo_base', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Tarifa GMP',
                'verbose_name_plural': 'Tarifario GMP',
                'unique_together': {('tipo_servicio', 'rango_buque', 'anio')},
            },
        ),
    ]
