# Generated by Django 5.2.2 on 2026-06-16 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cliente', '0003_cotizacionpendiente_tarifariogmp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Naviera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(blank=True, choices=[('verificacion', 'Verificación'), ('evaluacion', 'Evaluación')], help_text='Tipo de servicio según oficio de asignación de la autoridad', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('incompleto', 'Incompleto - Rechazado'), ('pendiente_servicio', 'Pendiente - Tipo de servicio no definido'), ('procesado', 'Procesado'), ('generado_auto', 'Generado Automáticamente'), ('aprobado', 'Aprobado'), ('enviado_cliente', 'Enviado al Cliente')], default='pendiente', max_length=30)),
                ('cotizacion_generada', models.BooleanField(default=False)),
                ('generado_automaticamente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('formulario_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_generadas', to='portal_cliente.entregable')),
            ],
        ),
    ]
