# Generated by Django 5.2.2 on 2026-08-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_cliente', '0005_remove_orphan_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacionmia',
            name='numero_whatsapp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacionpendiente',
            name='eslora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='cotizacionpendiente',
            name='notas_auditor',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cotizacionpendiente',
            name='rango_buque',
            field=models.CharField(blank=True, choices=[('grande', 'Grandes y Complejos (>80m)'), ('mediano', 'Medianos y Especializados (<=80m, múltiples cubiertas)'), ('pequeno', 'Pequeños y Especializados (<=80m, cubierta simple)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tarifariogmp',
            name='rango_buque',
            field=models.CharField(choices=[('grande', 'Grandes y Complejos (>80m)'), ('mediano', 'Medianos y Especializados (<=80m, múltiples cubiertas)'), ('pequeno', 'Pequeños y Especializados (<=80m, cubierta simple)')], max_length=20),
        ),
    ]
