# Generated by Django 5.0.6 on 2026-03-31 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoPBIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Naviera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=255)),
                ('contacto_principal', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_buque', models.CharField(max_length=255)),
                ('OMI', models.CharField(max_length=50)),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buques', to='naviera_registro.naviera')),
            ],
        ),
        migrations.CreateModel(
            name='RequisitoBuque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('COTIZACION', 'Formulario de Cotización'), ('DOCUMENTAL', 'Verificación Documental PBIP'), ('ADMINISTRATIVO', 'Expediente Administrativo')], max_length=20)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='expedientes_pre_servicio/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('buque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='naviera_registro.buque')),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisMIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_tecnico', models.TextField(blank=True, null=True)),
                ('alertas', models.TextField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_mia', to='naviera_registro.requisitobuque')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEntregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFORME_PBIP', 'Informe PBIP Terminado'), ('FACTURA', 'Factura'), ('COMPROBANTE_PAGO', 'Comprobante de Pago')], max_length=20)),
                ('archivo', models.FileField(upload_to='entregables/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('buque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='naviera_registro.buque')),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='naviera_registro.naviera')),
            ],
            options={
                'unique_together': {('naviera', 'buque', 'tipo')},
            },
        ),
    ]
