# Generated by Django 5.2.2 on 2026-04-24 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitobuque',
            name='naviera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos_los_requisitos', to='naviera_registro.naviera'),
        ),
    ]
