# Generated by Django 5.2.2 on 2026-03-26 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoBuque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('COTIZACION', 'Formulario de Cotización'), ('DOCUMENTAL', 'Verificación Documental PBIP'), ('ADMINISTRATIVO', 'Expediente Administrativo')], max_length=20)),
                ('nombre_documento', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='expedientes_pre_servicio/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('buque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='naviera_registro.buque')),
            ],
        ),
    ]
