# Generated by Django 5.2.2 on 2026-06-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0002_requisitobuque_naviera'),
    ]

    operations = [
        migrations.AddField(
            model_name='buque',
            name='metodo_pago',
            field=models.CharField(choices=[('100', '100%'), ('50_50', '50% - 50%')], default='100', max_length=10),
        ),
        migrations.AddField(
            model_name='buque',
            name='pago_1_completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buque',
            name='pago_2_completado',
            field=models.BooleanField(default=False),
        ),
    ]
