# Generated by Django 5.2.2 on 2026-03-26 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0002_requisitobuque'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoPBIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='requisitobuque',
            name='buque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='naviera_registro.buque'),
        ),
    ]
