# Generated by Django 5.2.2 on 2026-06-05 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0003_buque_metodo_pago_buque_pago_1_completado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naviera',
            name='alta_completa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='naviera',
            name='fecha_alta_completa',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
