# Generated by Django 5.2.2 on 2026-03-27 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0003_puntopbip_alter_requisitobuque_buque'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEntregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INFORME_PBIP', 'Informe PBIP Terminado'), ('FACTURA', 'Factura'), ('COMPROBANTE_PAGO', 'Comprobante de Pago')], max_length=20)),
                ('archivo', models.FileField(upload_to='entregables/%Y/%m/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('buque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='naviera_registro.buque')),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='naviera_registro.naviera')),
            ],
            options={
                'unique_together': {('naviera', 'buque', 'tipo')},
            },
        ),
    ]
