# Generated by Django 5.2.2 on 2026-03-28 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0004_documentoentregable'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisMIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_tecnico', models.TextField(blank=True, null=True)),
                ('alertas', models.TextField(blank=True, null=True)),
                ('procesado', models.BooleanField(default=False)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_mia', to='naviera_registro.requisitobuque')),
            ],
        ),
    ]
