# Generated by Django 5.2.2 on 2026-06-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0004_naviera_alta_completa_naviera_fecha_alta_completa'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentoentregable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentoentregable',
            name='secuencia',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='documentoentregable',
            unique_together={('naviera', 'buque', 'tipo', 'secuencia')},
        ),
    ]
