# Generated by Django 5.2.2 on 2026-06-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0005_alter_documentoentregable_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoentregable',
            name='tipo',
            field=models.CharField(choices=[('COTIZACION', 'Propuesta Económica (Cotización)'), ('INFORME_PBIP', 'Informe PBIP Terminado'), ('FACTURA', 'Factura'), ('COMPROBANTE_PAGO', 'Comprobante de Pago')], max_length=20),
        ),
    ]
