# Generated by Django 5.2.2 on 2026-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0006_alter_documentoentregable_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoentregable',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='entregables/xmls/', verbose_name='Archivo XML (Opcional)'),
        ),
    ]
