# Generated by Django 5.2.2 on 2026-06-06 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0007_documentoentregable_archivo_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitobuque',
            name='motivo_rechazo',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de rechazo/eliminación'),
        ),
    ]
