# Generated by Django 5.2.2 on 2026-06-14 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0008_requisitobuque_motivo_rechazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='naviera',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
