# Generated by Django 5.2.2 on 2026-06-25 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0010_naviera_tipo_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='naviera',
            name='tipo_servicio',
        ),
    ]
