# Generated by Django 5.2.2 on 2026-08-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0011_remove_naviera_tipo_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='buque',
            name='notificaciones_activas',
            field=models.BooleanField(default=True, verbose_name='Recibir recordatorios de documentación PBIP'),
        ),
        migrations.AddField(
            model_name='naviera',
            name='notificaciones_activas',
            field=models.BooleanField(default=True, verbose_name='Recibir recordatorios automáticos (WhatsApp/Email)'),
        ),
    ]
