# Generated by Django 5.2.2 on 2026-08-19 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naviera_registro', '0012_buque_notificaciones_activas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitobuque',
            name='hash_coincide_con_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados_posteriores', to='naviera_registro.requisitobuque', verbose_name='Coincide con este documento anterior (mismo hash)'),
        ),
        migrations.AddField(
            model_name='requisitobuque',
            name='hash_documento',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
